name: geo_fire_fz
description: GeoFlutterFire is an open-source library that allows you to store and query firestore documents based on their geographic location.
version: 3.0.3
homepage: https://github.com/axnguyenit/geo_fire_fz

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.3.1
  rxdart: ^0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter
